using Azure.Identity;
using System.ComponentModel.DataAnnotations;

namespace FundApp.Models
{
    public class Fundraiser
    {
        //fundraiserID, fundraiserDateCreated, and fundraiserStatus will be autogenerated by the DB during creation
        //fundraiserStatus and fundraiserDateCreated will be set to default values in
        //the DB, no need to send these values in the request
        [Key]
        public int? userID { get; set; }
        public string? fundraiserName { get; set; }
        public string? fundraiserSummary { get; set; }
        public double? fundraiserGoalAmount { get; set; }
        //The 4 variables above are required for fundraiser creation
        public int? fundraiserID { get; set; }
        public DateOnly? fundraiserDateCreated { get; set; }
        public string? fundraiserStatus { get; set; }
    }
}