using Azure.Identity;
using System.ComponentModel.DataAnnotations;

namespace FundApp.Models
{
    public class Fundraiser
    {
        //fundraiserID will be autogenerated by the DB
        //fundraiserStatus and fundraiserDateCreated will be set to default values in
        //the DB, no need to send these values in the request
        [Key]
        public int userID { get; set; } = -1;
        public string fundraiserName { get; set; } = "N/A";
        public string fundraiserSummary { get; set; } = "N/A";
        public double fundraiserGoalAmount { get; set; } = 0.00;
    }
}